### ISSUE TITLE
E aquele projeto que tem em java ?

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [m4rciosouza/restful-api-kotlin#1]
Professor esse projeto é o mesmo feito em java ?

**Comment by m4rciosouza** [comment]
É um projeto parecido com o do Java, mas escrito em Kotlin.

Márcio.

2018-01-15 14:32 GMT+00:00 Junior <notifications@github.com>:

**Comment by JoseRFJuniorLLMs** [comment]
Não acredito, o código muito limpo fácil entendimento, BEM MENOR...  Gritante....

Vou estudar ele Obrigado..
