### ISSUE TITLE
Autenticação Mistério ?

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [m4rciosouza/restful-api-kotlin#2]
Professor desculpa a burrice rs.. Mas eu não achei o usuário e senha gerado, já estudei 50% do código já até consigo estender e modificar, mas não consigo ver o resultado.
Quais os passo para conseguir por para rodar seu projeto ?

Obrigado.

![image](https://user-images.githubusercontent.com/488409/34980235-fde9b558-fa8a-11e7-8016-cf9a067f77a2.png)

**Comment by m4rciosouza** [comment]
Acabei me confundindo com a versão da API.

Essa API autentica na base de dados do MongoDB. Existe um documento chamado
Funcionario que contém os campos email e senha que são utilizados para a
autenticação (vide FuncionarioDetailsService.kt no pacotesecurity).

Adicione um novo funcionário na base de dados que conseguirá autenticar,
lembrando que a senha deverá estar no formato do BCrypt, igual encontrado
no arquivo SenhaUtils.kt.

Em 16 de janeiro de 2018 09:01, Junior <notifications@github.com> escreveu:

**Comment by JoseRFJuniorLLMs** [comment]
Muito estranho não loga, mas ta chegando até o banco !

USUÁRIO: Nome
SENHA:123456

`    private fun funcionario(): Funcionario =
            Funcionario("Nome", "email@email.com", SenhaUtils().gerarBCrypt("123456"),
                    "23145699876", PerfilEnum.ROLE_USUARIO, idFuncionario)

}`

Isso gera 👍 

`In BCrypt hashing algorithm, each time, a different hash value of length 60 is generated.

$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.
$2a$10$trT3.R/Nfey62eczbKEnueTcIbJXW.u1ffAo/XfyLpofwNDbEB86O
$2a$10$teJrCEnsxNT49ZpXU7n22O27aCGbVYYe/RG6/XxdWPJbOLZubLIi2
$2a$10$BHG59UT6p7bgT6U2fQ/9wOyTIdejh4Rk1vWilvl4b6ysNPdhnViUS
$2a$10$W9oRWeFmOT0bByL5fmAceucetmEYFg2yzq3e50mcu.CO7rUDb/poG
$2a$10$HApapHvDStTEwjjneMCvxuqUKVyycXZRfXMwjU0rRmaWMsjWQp/Zu
$2a$10$GYCkBzp2NlpGS/qjp5f6NOWHeF56ENAlHNuSssSJpE1MMYJevHBWO
$2a$10$gwbTCaIR/qE1uYhvEY6GG.bNDQcZuYQX9tkVwaK/aD7ZLPptC.7QC
$2a$10$5uKS72xK2ArGDgb2CwjYnOzQcOmB7CPxK6fz2MGcDBM9vJ4rUql36
$2a$10$6TajU85/gVrGUm5fv5Z8beVF37rlENohyLk3BEpZJFi6Av9JNkw9O`

No banco eu testei todas elas: RoboMongo

`{
    "_id" : ObjectId("5a5e6693b681cd4fbf335f28"),
    "nome" : "Nome",
    "email" : "email@email.com",
    "senha" : "$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.",
    "cpf" : "23145699876",
    "perfil" : "admin",
    "empresaId" : "1",
    "valorHora" : "1",
    "qtdhrastabalhoda" : "1",
    "qtdhrasamoco" : "1"
}`
![image](https://user-images.githubusercontent.com/488409/35013066-34dcb44e-faf3-11e7-9670-56c7821393db.png)


![image](https://user-images.githubusercontent.com/488409/35013073-40c9eef2-faf3-11e7-99dc-12c498407bd9.png)


![image](https://user-images.githubusercontent.com/488409/35013121-77ec2ac6-faf3-11e7-9183-1cb25f8386a2.png)

**Comment by JoseRFJuniorLLMs** [comment]
RESOLVIDO:
https://www.udemy.com/api-restful-kotlin-spring-boot-mongodb/
